---
- hosts: all
  sudo: yes
  gather_facts: yes
  tasks:
    - debug: msg="hostname = {{ ansible_hostname }}"
    - debug: msg="eth1.ipv4.address = {{ ansible_eth1.ipv4.address }}"
    - apt: name=apache2
    - service: name=apache2 state=restarted
    - template: src=index.html.j2 dest=/var/www/html/index.html
